# generate_summary.sh

#!/usr/bin/env bash

# This script scans the Rails application's common directories to identify models,
# controllers, services, and other key files. It attempts to extract:
# - File type (model, controller, service, etc.)
# - File path
# - Short description (taken from initial comments or class/module definition)
#
# The output is generated by the generate_summary function and is saved to app_summary.json.

set -e

BASE_DIR=$(pwd)
OUTPUT_FILE="app_summary.json"

# Function to extract a short description from a file
extract_description() {
  local file_path="$1"
  # Extract initial comments or the first class/module line
  local head_lines
  head_lines=$(head -n 10 "$file_path")

  # Extract comment lines or class/module definitions
  local doc
  doc=$(echo "$head_lines" | grep -E '^#|^\s*(class|module)' | sed 's/^[#[:space:]]*//g' | tr '\n' ' ')

  if [ -z "$doc" ]; then
    doc="No top-level documentation found."
  fi

  echo "$doc"
}

# Function to process a given directory and file type
process_directory() {
  local dir_path="$1"
  local file_type="$2"

  find "$dir_path" -type f -name "*.rb" | sort | while read -r file; do
    [ -f "$file" ] || continue
    local desc
    desc=$(extract_description "$file")
    local relative_path
    relative_path=$(realpath --relative-to="$BASE_DIR" "$file")

    echo "    {"
    echo "      \"path\": \"${relative_path}\","
    echo "      \"type\": \"${file_type}\","
    echo "      \"description\": \"${desc}\""
    echo "    },"
  done
}

# Function that generates the summary and prints to stdout
generate_summary() {
  echo "{"
  echo "  \"files\": ["

  if [ -d "app/models" ]; then
    process_directory "app/models" "model"
  fi

  if [ -d "app/controllers" ]; then
    process_directory "app/controllers" "controller"
  fi

  if [ -d "app/services" ]; then
    process_directory "app/services" "service"
  fi

  if [ -d "app/views" ]; then
    find "app/views" -type f \( -name "*.erb" -o -name "*.haml" -o -name "*.html" \) | sort | while read -r file; do
      local relative_path
      relative_path=$(realpath --relative-to="$BASE_DIR" "$file")
      echo "    {"
      echo "      \"path\": \"${relative_path}\","
      echo "      \"type\": \"view\","
      echo "      \"description\": \"View template for rendering UI.\""
      echo "    },"
    done
  fi

  # Close the JSON array and object
  # We'll remove the trailing comma from the last entry in the array
  echo "  ]"
  echo "}" | sed '$!N; s/},\n  ]/}\n  ]/'
}

# Generate the summary and save to the output file
generate_summary > "$OUTPUT_FILE"

echo "Summary generated and saved to $OUTPUT_FILE."
